cubes:
  - name: products
    sql_table: public.products
    description: Product catalog information

    dimensions:
      - name: id
        sql: "{CUBE}.id"
        type: number
        primary_key: true

      - name: name
        sql: "{CUBE}.name"
        type: string
        description: Product name

      - name: description
        sql: "{CUBE}.description"
        type: string
        description: Product description

      - name: supplier_id
        sql: "{CUBE}.supplier_id"
        type: number

      - name: product_category_id
        sql: "{CUBE}.product_category_id"
        type: number

      - name: created_at
        sql: "{CUBE}.created_at"
        type: time

    measures:
      - name: count
        type: count
        description: Total number of products

    joins:
      - name: product_categories
        sql: "{CUBE}.product_category_id = {product_categories.id}"
        relationship: many_to_one

      - name: suppliers
        sql: "{CUBE}.supplier_id = {suppliers.id}"
        relationship: many_to_one
