views:
  - name: orders_view
    description: Comprehensive view of order data with key metrics

    cubes:
      - join_path: orders
        includes:
          # Dimensions
          - id
          - number
          - status
          - created_at
          - completed_at

          # Measures  
          - count
          - completed_count
          - shipped_count
          - cancelled_count
